### ISSUE TITLE
Photoshop groups support

### ISSUE THREAD

**Issue by tdakkota** [chinedufn/psd#10]
Layer should have group_id field.

**Comment by chinedufn** [comment]
This is in the image resources section which we haven't started parsing - https://github.com/chinedufn/psd/blob/cd3b04af2e91b5645dfe29a932c3005087d39e94/src/sections/mod.rs#L89

**Comment by tdakkota** [comment]
Well, I did a little research. 
Groups are present as two layers with `Section divider setting (Photoshop 6.0)` tagged block and with layers between them.

![image](https://user-images.githubusercontent.com/15220500/78463662-390f0f80-76e8-11ea-8fc1-a6eca5f3d311.png)


So, a simple PSD file with one layer inside group have this structure(layers are present in reverse order, you know):
```
- name: </Layer group>, with tag `lsct`, divider_type is `closed folder`
- name: First Layer, without tag `lsct`
- name: group, with tag `lsct`, divider_type is `open folder`
```
 
![image](https://user-images.githubusercontent.com/15220500/78463677-68258100-76e8-11ea-84e8-3cf3232c813a.png)

**Comment by chinedufn** [comment]
Ah nice - so layers are surrounding by an open and close tag.

Nice find!
