### ISSUE TITLE
Unicode string may have no paddings

### ISSUE THREAD

**Issue by gyk** [chinedufn/psd#34]
I have a PSD file where the unicode string inside `luni` additional layer info has neither null bytes nor paddings:

```
38 42 49 4D 6C 75 6E 69 00 00 00 06 00 00 00 01 00 31    8BIMluni.........1
```

However, the current implementation decodes it as a unicode string with a padding length of 4: https://github.com/chinedufn/psd/blob/master/src/sections/layer_and_mask_information_section/mod.rs#L424, so all the parsed data after it are messed up.

It seems unicode string may or may not have paddings, depending on the section length and the absolute position of file cursor. References:

- https://github.com/MolecularMatters/psd_sdk/blob/310d06e/src/Psd/PsdParseLayerMaskSection.cpp#L725
- https://github.com/haraldk/TwelveMonkeys/blob/twelvemonkeys-3.8.2/imageio/imageio-psd/src/main/java/com/twelvemonkeys/imageio/plugins/psd/PSDLayerInfo.java#L147

Just seeking to `beginning_position + additional_layer_info_len` seems to be the easiest solution.

**Comment by chinedufn** [comment]
Ah, thanks for the bug report. I'd be happy to review a PR that fixes this!

**Comment by gyk** [comment]
Besides 'luni', I'm not sure whether the unicode string of "name from classID" uses paddings. PSD.rb apparently reads no paddings: [link](https://github.com/layervault/psd.rb/blob/v3.9.0/lib/psd/descriptor.rb#L33). Maybe `read_unicode_string` should default to `read_unicode_string_padding(1)`?

**Comment by chinedufn** [comment]
Ah, thanks for researching this!

I think we'd just want to add test fixture PSDs with different layer types and see whether or not they pass. 
Then if they fail modify the code to make them pass.
