### ISSUE TITLE
Request: Make the project fundable / accept donations / etc

### ISSUE THREAD

**Issue by Phrohdoh** [chinedufn/psd#6]
Please see https://web.archive.org/web/20170701063840id_/http://blog.pinboard.in/2011/12/don_t_be_a_free_user/ to understand why I'm requesting this. :-)

While this project doesn't currently incur costs from hosting/etc, you are spending your time on it and the open-source community should support that.

**Comment by chinedufn** [comment]
On interesting link! I actually have a GitHub Sponsors page https://github.com/sponsors/chinedufn - is that sort of what you mean?

Cheers!

**Comment by Phrohdoh** [comment]
Yes!  If you set that up for this repo you'll get a 'Sponsor' button before the 'Watch' button that people can easily find. :-)

**Comment by chinedufn** [comment]
Ahhh didn't know about that - thank you!
